# Generated by Django 5.0.14 on 2025-10-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('capacity', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=1)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Lecture Hall', 'Lecture Hall'), ('Laboratory', 'Laboratory'), ('Office', 'Office'), ('Conference', 'Conference'), ('Other', 'Other')], default='Classroom', max_length=50)),
                ('capacity', models.IntegerField(default=30)),
                ('equipment', models.TextField(blank=True, help_text='Comma-separated list of equipment')),
                ('description', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='facilities.building')),
            ],
            options={
                'ordering': ['building', 'room_number'],
            },
        ),
    ]
