# Generated by Django 5.0.14 on 2025-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Academic', 'Academic'), ('Social', 'Social'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Workshop', 'Workshop'), ('Meeting', 'Meeting'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('registered', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('aid_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Grant', 'Grant'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan'), ('Work Study', 'Work Study')], max_length=20)),
                ('name', models.CharField(help_text='Name of grant/scholarship/loan', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Financial aid',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='ParkingPermit',
            fields=[
                ('permit_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('permit_type', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Visitor', 'Visitor')], default='Student', max_length=20)),
                ('lot_number', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
