# Generated by Django 5.0.14 on 2025-10-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aid', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='parkingpermit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='users.studentprofile'),
        ),
    ]
