# Generated by Django 5.0.14 on 2025-10-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('head', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('section_number', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('Fall 2024', 'Fall 2024'), ('Spring 2025', 'Spring 2025'), ('Summer 2024', 'Summer 2024'), ('Fall 2025', 'Fall 2025')], max_length=20)),
                ('year', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_rank', models.CharField(max_length=50)),
                ('meeting_days', models.CharField(max_length=20)),
                ('meeting_time', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=30)),
                ('enrolled', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
            ],
            options={
                'ordering': ['semester', 'course'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('description', models.TextField()),
                ('prerequisites', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.department')),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed')], default='Enrolled', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('W', 'W'), ('I', 'I'), ('P', 'P')], max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('credits_attempted', models.IntegerField(default=0)),
                ('credits_earned', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
